package com.example.ticketingsystem

data class Movie(
    val id: Int,
    val title: String,
    val imageRes: Int,
    val rating: Float,
    val votes: Int,
    val dimension: String,
    val language: String,
    val runtime: String,
    val description: String,
    val certificate: String,
    val releaseDate: String,
    val genres: List<String>
)

val fakeMovieData  = listOf(Movie(
        1,
        "Tillu Square",
        R.drawable.tillu2,
        7.3f,
        96600,
        "2D",
        "Telugu",
        "2h 3m",
        "Follow Tillu as his life is upended by a mysterious murder, plunging him into a perilous journey of discovery and danger.",
        "UA",
        "29 Mar, 2024",
        listOf("Action", "Comedy", "Romantic")
    ), Movie(
        2,
        "Manjummel Boys",
        R.drawable.manjummel,
        8.5f,
        19869,
        "2D",
        "Malayalam",
        "2h 15m",
        "A group of friends get into a daring rescue mission to save their friend from Guna Caves, a perilously deep pit from where nobody has ever been brought back.",
        "U",
        "5 Apr, 2024",
        listOf("Adventure", "Drama", "Thriller")
    ), Movie(
        3,
        "Premalu",
        R.drawable.premalu,
        8.9f,
        99895,
        "2D",
        "Malayalam",
        "2h 36m",
        "Sachin pursues romance but finds himself caught between two potential partners, leading to amusing complications.",
        "U",
        "9 Feb, 2024",
        listOf("Comedy", "Romantic")
    ), Movie(
        4,
        "Rockstar",
        R.drawable.rockstar,
        7.9f,
        199742,
        "2D",
        "Hindi",
        "2h 39m",
        "The film follows Janardhan Jhakar in a series of flashbacks and flash forwards, how the small collage boy became an international rock sensation \"Jordan\".",
        "UA",
        "11 Nov, 2011",
        listOf("Drama", "Musical, Romantic")
    ), Movie(
        5,
        "RRR",
        R.drawable.rrr,
        8.7f,
        299568,
        "2D",
        "Telugu",
        "3h 7m",
        "A fearless warrior on a perilous mission comes face to face with a steely cop serving British forces in this epic saga set in pre-independent India.",
        "UA",
        "25 Mar, 2022",
        listOf("Action", "Drama", "Historical", "Period")
    ), Movie(
        6,
        "Whiplash",
        R.drawable.whiplash,
        9.5f,
        457531,
        "2D",
        "English",
        "1h 46m",
        "Nineteen-year-old Andrew Niemann wants to be the greatest jazz drummer in the world, in a league with Buddy Rich.",
        "A",
        "20 Feb, 2015",
        listOf("Drama")
    ), Movie(
        7,
        "Zindagi Na Milegi Dobara",
        R.drawable.zindagi,
        8.2f,
        327800,
        "2D",
        "Hindi",
        "2h 35m",
        "Three friends who were inseparable in childhood decide to go on a three-week-long bachelor road trip to Spain, in order to re-establish their bond and explore thrilling adventures, before one of them gets married.",
        "UA",
        "15 Jul, 2011",
        listOf("Adventure", "Comedy", "Drama")
    ), Movie(
        8,
        "Ee Nagaraniki Em Ayindhi",
        R.drawable.ee,
        9.0f,
        204800,
        "2D",
        "Telugu",
        "2h 2m",
        "The story is based on four childhood friends who go on a trip to Goa. Each have their own dream careers, and collaborate to make a short film.",
        "UA",
        "29 Jun, 2018",
        listOf("Comedy", "Drama")
    ), Movie(
        9,
        "Godzilla vs Kong",
        R.drawable.godzilla,
        6.7f,
        308210,
        "3D",
        "English",
        "1h 55m",
        "The new installment in the Monsterverse puts the mighty Kong and the fearsome Godzilla against a colossal deadly threat hidden within our world that threatens the existence of their species and our very own.",
        "UA",
        "29 Mar, 2024",
        listOf("Action", "Sci-Fi", "Thriller")
    ),)